// Single source of truth for every chart's header: which series exist, what
// they mean, the metric formula (for the ? popover), and whether the chart
// participates in the synced crosshair group.

export interface SeriesDef {
  key: string // dataKey on the chart row
  label: string // chip text, e.g. 'in'
  color: string // CSS var, e.g. 'var(--color-chart-1)'
  definition: string // shown on chip hover (title)
  axis?: 'left' | 'right' // dual-axis charts only
  dashed?: boolean // rendered as a dashed line (e.g. quality)
}

export interface ChartMeta {
  id: string
  title: string
  caption: string // the // line under the title
  series: SeriesDef[]
  formula?: { label: string; body: string } // ? popover content
  syncGroup?: string // shared recharts syncId; omit for standalone charts
}

const DAILY_SYNC = 'productivity-daily'

export const tokensPerDayMeta: ChartMeta = {
  id: 'tokens-per-day',
  title: 'tokens per day',
  caption: 'input + output tokens per day · ⚑ = ecosystem change',
  syncGroup: DAILY_SYNC,
  series: [
    {
      key: 'tokensIn',
      label: 'in',
      color: 'var(--color-chart-1)',
      definition: 'prompt tokens sent to the model',
    },
    {
      key: 'tokensOut',
      label: 'out',
      color: 'var(--color-chart-2)',
      definition: 'tokens generated by the model',
    },
  ],
}

export const kpiMeta: ChartMeta = {
  id: 'kpi',
  title: 'token efficiency',
  caption: 'token efficiency vs frozen baseline · 100% = baseline · ⚑ = ecosystem change',
  syncGroup: DAILY_SYNC,
  formula: {
    label: 'Token Efficiency',
    body: 'Token Efficiency = expected ÷ actual tokens × 100, vs a frozen baseline. 100% = on baseline; higher = more efficient (fewer tokens than expected for the task difficulty).',
  },
  series: [
    {
      key: 'kpi',
      label: 'Eff',
      color: 'var(--color-chart-1)',
      definition: 'efficiency % vs frozen baseline',
      axis: 'left',
    },
    {
      key: 'quality',
      label: 'quality',
      color: 'var(--color-chart-2)',
      definition: 'avg user rating 0–10 (rated sessions only)',
      axis: 'right',
      dashed: true,
    },
  ],
}

export const todayByHourMeta: ChartMeta = {
  id: 'today-by-hour',
  title: 'today by hour',
  caption: 'current local day · ignores the range above',
  series: [
    {
      key: 'tokensIn',
      label: 'in',
      color: 'var(--color-chart-1)',
      definition: 'prompt tokens sent to the model',
    },
    {
      key: 'tokensOut',
      label: 'out',
      color: 'var(--color-chart-2)',
      definition: 'tokens generated by the model',
    },
  ],
}

export const eventsPerDayMeta: ChartMeta = {
  id: 'events-per-day',
  title: 'events per day',
  caption: 'agent runs per day · last 30 days',
  series: [
    {
      key: 'count',
      label: 'events',
      color: 'var(--color-chart-1)',
      definition: 'number of agent runs that day',
    },
  ],
}

export const CHART_METAS: Record<string, ChartMeta> = {
  [tokensPerDayMeta.id]: tokensPerDayMeta,
  [kpiMeta.id]: kpiMeta,
  [todayByHourMeta.id]: todayByHourMeta,
  [eventsPerDayMeta.id]: eventsPerDayMeta,
}
